'use strict';

module.exports = {
    CACHE_NAME : {
        CHAMPION_ALL_ALL : 'CHAMPION_ALL_ALL',
        CHAMPION_INFO_ALL : 'CHAMPION_INFO_ALL',
        CHAMPION_STATS_ALL : 'CHAMPION_STATS_ALL',
        CHAMPION_SPELLS_ALL : 'CHAMPION_SPELLS_ALL',
    },
};
